[BitTorrent]
Session\DefaultSavePath=/qar/downloads
Session\Port=9978
Session\QueueingSystemEnabled=false

[Meta]
MigrationVersion=4

[Network]
Cookies=@Invalid()

[Preferences]
WebUI\AuthSubnetWhitelist=127.0.0.1/32, ::1/128, 10.0.0.0/8, 172.16.0.0/12, 192.168.0.0/16
WebUI\AuthSubnetWhitelistEnabled=true
WebUI\CSRFProtection=false
WebUI\HostHeaderValidation=false
WebUI\LocalHostAuth=false
WebUI\Port=8888
